# Generated by Django 4.0.7 on 2022-08-17 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redpanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Har',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_jumat', models.DateField(verbose_name='Tanggal Mulai')),
                ('jumat', models.CharField(choices=[('Standby', 'Standby'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM')], default='Standby', max_length=20, verbose_name='Jumat')),
                ('sabtu', models.CharField(choices=[('Standby', 'Standby'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM')], default='Standby', max_length=20, verbose_name='Sabtu')),
                ('minggu', models.CharField(choices=[('Standby', 'Standby'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM')], default='Standby', max_length=20, verbose_name='Minggu')),
                ('senin', models.CharField(choices=[('Standby', 'Standby'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM')], default='Standby', max_length=20, verbose_name='Senin')),
                ('selasa', models.CharField(choices=[('Standby', 'Standby'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM')], default='Standby', max_length=20, verbose_name='Selasa')),
                ('rabu', models.CharField(choices=[('Standby', 'Standby'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM')], default='Standby', max_length=20, verbose_name='Rabu')),
                ('kamis', models.CharField(choices=[('Standby', 'Standby'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('TO', 'TO'), ('SO', 'SO'), ('MO', 'MO'), ('PdM', 'PdM'), ('CM', 'CM')], default='Standby', max_length=20, verbose_name='Kamis')),
                ('mesin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redpanda.mesin', verbose_name='Nama Mesin')),
            ],
        ),
    ]
