# Generated by Django 4.0.7 on 2022-08-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redpanda', '0002_har'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_cost', models.IntegerField(blank=True, null=True, verbose_name='Total Fix Cost')),
                ('time_base_vcost', models.IntegerField(blank=True, null=True, verbose_name='Total Time Base V-Cost')),
                ('sfc_50', models.IntegerField(blank=True, null=True, verbose_name='SFC 50% DMN')),
                ('sfc_75', models.IntegerField(blank=True, null=True, verbose_name='SFC 75% DMN')),
                ('sfc_100', models.IntegerField(blank=True, null=True, verbose_name='SFC 100% DMN')),
                ('harga_sewa', models.IntegerField(blank=True, null=True, verbose_name='Harga Sewa per kWh (Khusus Sewa)')),
                ('pajak_air', models.IntegerField(blank=True, null=True, verbose_name='Pajak Air Permukaan')),
                ('susut_trafo', models.IntegerField(blank=True, null=True, verbose_name='Susut Trafo')),
                ('susut_jaringan', models.IntegerField(blank=True, null=True, verbose_name='Susut Jaringan (%)')),
                ('mesin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redpanda.mesin', verbose_name='Nama Mesin')),
            ],
        ),
    ]
