# Generated by Django 4.0.7 on 2022-08-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redpanda', '0003_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='tanggal',
            field=models.DateField(auto_now=True, verbose_name='Tanggal Input'),
        ),
    ]
