# Generated by Django 4.0.7 on 2022-09-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redpanda', '0004_cost_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='harga_sewa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Harga Sewa per kWh'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='sfc_100',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='SFC 100% DMN'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='sfc_50',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='SFC 50% DMN'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='sfc_75',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='SFC 75% DMN'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='susut_jaringan',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Susut Jaringan (%)'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='susut_trafo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Susut Trafo'),
        ),
    ]
