# Generated by Django 4.0.7 on 2022-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redpanda', '0004_cost_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='fix_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Fix Cost'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='harga_sewa',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Harga Sewa per kWh (Khusus Sewa)'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='pajak_air',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pajak Air Permukaan'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='sfc_100',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='SFC 100% DMN'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='sfc_50',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='SFC 50% DMN'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='sfc_75',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='SFC 75% DMN'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='susut_jaringan',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Susut Jaringan (%)'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='susut_trafo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Susut Trafo'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='time_base_vcost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Time Base V-Cost'),
        ),
    ]
